# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}

dotenv:
  - ".env"

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  run_server:
    cmds:
      - air run ./cmd/app/main.go

  migrate_new:
    desc: Create a new migration (e.g. task migrate_new -- init_schema)
    cmds:
      - DATABASE_URL={{ .DATABASE_URL }} dbmate new "{{.CLI_ARGS}}"

  migrate_up:
    desc: Run migrations
    cmds:
      - DATABASE_URL={{ .DATABASE_URL }} dbmate up

  migrate_down:
    desc: Rollback last migration
    cmds:
      - DATABASE_URL={{ .DATABASE_URL }} dbmate down

  create_db:
    desc: Create database
    cmds:
      - DATABASE_URL={{ .DATABASE_URL }} dbmate create

  drop_db:
    desc: Drop database
    cmds:
      - DATABASE_URL={{ .DATABASE_URL }} dbmate drop

  reset_db:
    desc: Reset database
    cmds:
      - task drop_db
      - task create_db
      - task migrate_up
